backend:
  name: github
  repo: yocreativewatch-arch/my-watch
  branch: main

media_folder: "" 
public_folder: ""

collections:
  - name: "watch"
    label: "จัดการ SKU นาฬิกา"
    folder: "watches"
    create: true
    fields:
      - {label: "ชื่อรุ่น (Name)", name: "title", widget: "string"}
      - {label: "ราคา (Price)", name: "price", widget: "string"}
      - {label: "รูปภาพ (Image)", name: "image", widget: "image"}
      - {label: "รายละเอียดเครื่อง/วัสดุ", name: "body", widget: "markdown"}
